"""
Generate interactive HTML dossiers
"""
import json


class HTMLDossier:
    def generate(self, identity_graph: dict, findings: dict) -> str:
        target = findings.get('target', {})
        findings_data = findings.get('findings', {})
        confidence = findings.get('confidence_score', 0)
        generated_at = findings.get('generated_at', 'N/A')
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OmniTrace Dossier - {target.get('name', 'Unknown')}</title>
    <script src="https://d3js.org/d3.v7.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
        body {{ font-family: 'Inter', sans-serif; }}
        .gradient-bg {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); }}
        .card {{ background: #1f2937; border-radius: 0.75rem; padding: 1.5rem; margin-bottom: 1.5rem; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.3); border: 1px solid #374151; }}
        .section-title {{ font-size: 1.25rem; font-weight: 600; margin-bottom: 1rem; color: #60a5fa; display: flex; align-items: center; gap: 0.5rem; }}
        .profile-row {{ display: flex; justify-content: space-between; align-items: center; padding: 0.75rem 0; border-bottom: 1px solid #374151; }}
        .profile-row:last-child {{ border-bottom: none; }}
        .badge {{ padding: 0.25rem 0.75rem; border-radius: 9999px; font-size: 0.75rem; font-weight: 500; }}
        .badge-success {{ background: #065f46; color: #6ee7b7; }}
        .badge-warning {{ background: #92400e; color: #fcd34d; }}
        .badge-danger {{ background: #991b1b; color: #fca5a5; }}
        .badge-info {{ background: #1e40af; color: #93c5fd; }}
        .badge-gray {{ background: #374151; color: #d1d5db; }}
        .stat-card {{ background: linear-gradient(135deg, #1e3a8a 0%, #312e81 100%); border-radius: 0.5rem; padding: 1rem; text-align: center; }}
        .stat-value {{ font-size: 1.5rem; font-weight: bold; color: #60a5fa; }}
        .stat-label {{ font-size: 0.75rem; color: #9ca3af; text-transform: uppercase; letter-spacing: 0.05em; }}
        .graph-container {{ background: #111827; border-radius: 0.5rem; padding: 1rem; }}
        a {{ color: #60a5fa; text-decoration: none; }}
        a:hover {{ color: #93c5fd; text-decoration: underline; }}
        .icon {{ width: 1.25rem; height: 1.25rem; display: inline-block; }}
    </style>
</head>
<body class="bg-gray-900 text-gray-100">
    <!-- Header -->
    <div class="gradient-bg text-white py-8 px-8 shadow-lg">
        <div class="container mx-auto max-w-6xl">
            <div class="flex justify-between items-center">
                <div>
                    <h1 class="text-4xl font-bold mb-2"><i class="fas fa-user-secret mr-3"></i>Identity Dossier</h1>
                    <p class="text-blue-100">Generated by OmniTrace on {generated_at}</p>
                </div>
                <div class="text-right">
                    <div class="text-sm text-blue-100 mb-1">Confidence Score</div>
                    <div class="text-4xl font-bold text-white">{confidence}</div>
                </div>
            </div>
        </div>
    </div>

    <div class="container mx-auto p-8 max-w-6xl">
        <!-- Target Summary Cards -->
        <div class="grid grid-cols-4 gap-4 mb-8">
            <div class="stat-card">
                <div class="stat-value">{target.get('name', 'N/A').split()[0] if target.get('name') else 'N/A'}</div>
                <div class="stat-label">Name</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">{len(findings_data.get('social', {}))}</div>
                <div class="stat-label">Social Profiles</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">{sum(1 for v in findings_data.get('username_matches', {}).values() if v.get('found'))}</div>
                <div class="stat-label">Platforms Found</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">{sum(v.get('breaches_found', 0) for v in findings_data.get('breaches', {}).values())}</div>
                <div class="stat-label">Breaches</div>
            </div>
        </div>

        <!-- Target Information -->
        <div class="card">
            <div class="section-title"><i class="fas fa-bullseye"></i> Target Information</div>
            <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
                {self._render_field('Name', target.get('name'), 'fa-user')}
                {self._render_field('Email', target.get('email'), 'fa-envelope')}
                {self._render_field('Phone', target.get('phone'), 'fa-phone')}
                {self._render_field('Username', target.get('username'), 'fa-at')}
            </div>
        </div>

        <!-- People Search -->
        {self._render_people_search(findings_data.get('people_search'))}

        <!-- Social Media -->
        {self._render_social_profiles(findings_data.get('social', {}))}

        <!-- Email Intel -->
        {self._render_email_intel(findings_data.get('email_info'))}

        <!-- Phone Intel -->
        {self._render_phone_intel(findings_data.get('phone_info'))}

        <!-- Username Matches -->
        {self._render_username_matches(findings_data.get('username_matches', {}))}

        <!-- Breach Data -->
        {self._render_breaches(findings_data.get('breaches', {}))}

        <!-- Dark Web -->
        {self._render_darkweb(findings_data.get('darkweb'))}

        <!-- Face Matches -->
        {self._render_face_matches(findings_data.get('face_matches'))}

        <!-- Reverse Image -->
        {self._render_reverse_image(findings_data.get('reverse_image'))}

        <!-- EXIF Data -->
        {self._render_exif(findings_data.get('exif'))}

        <!-- Relationship Graph -->
        {self._render_graph(identity_graph)}

        <footer class="text-center text-gray-500 text-sm mt-8 pb-4">
            <i class="fas fa-shield-alt"></i> OmniTrace - For Authorized OSINT & Security Research Only
        </footer>
    </div>
</body>
</html>"""
        return html

    def _render_field(self, label, value, icon=''):
        if not value:
            return ''
        icon_html = f'<i class="fas {icon} text-gray-400 mr-2"></i>' if icon else ''
        return f'<div class="bg-gray-800 p-3 rounded-lg"><div class="text-xs text-gray-400 mb-1">{icon_html}{label}</div><div class="font-medium text-sm break-all">{value}</div></div>'

    def _render_people_search(self, data):
        if not data:
            return ''
        results = data.get('results', [])
        rows = ''
        for r in results:
            conf = r.get('confidence', 0)
            conf_class = 'badge-success' if conf >= 0.7 else ('badge-warning' if conf >= 0.5 else 'badge-info')
            rows += f"""
            <div class="profile-row">
                <div class="flex-1">
                    <div class="font-medium text-white">{r.get('source', 'Unknown')}</div>
                    <div class="text-sm text-gray-400">{r.get('occupation', '')} {r.get('age', '')}</div>
                </div>
                <div class="text-right">
                    <div class="text-sm text-gray-300">{', '.join(r.get('locations', []))}</div>
                    <span class="badge {conf_class} mt-1 inline-block">{conf}</span>
                </div>
            </div>"""
        return f"""
        <div class="card">
            <div class="section-title"><i class="fas fa-search"></i> People Search ({data.get('query', 'N/A')})</div>
            <div class="text-sm text-gray-400 mb-4">Total results: {data.get('total_results', 0)}</div>
            {rows}
        </div>"""

    def _render_social_profiles(self, social):
        if not social:
            return ''
        rows = ''
        found_count = 0
        for platform, data in social.items():
            if data.get('found'):
                found_count += 1
                verified = '<i class="fas fa-check-circle text-blue-400 ml-1"></i>' if data.get('verified') else ''
                rows += f"""
                <div class="profile-row">
                    <div class="flex items-center gap-2">
                        <i class="fab fa-{platform} text-gray-400 icon"></i>
                        <span class="font-medium capitalize">{platform}</span>
                        {verified}
                        <span class="badge badge-success">Found</span>
                    </div>
                    <a href="{data.get('url', '#')}" target="_blank" class="text-blue-400 hover:text-blue-300 text-sm">
                        {data.get('url', 'N/A')} <i class="fas fa-external-link-alt ml-1"></i>
                    </a>
                </div>"""
        return f"""
        <div class="card">
            <div class="section-title"><i class="fas fa-share-alt"></i> Social Media Profiles</div>
            <div class="text-sm text-gray-400 mb-4">{found_count} profiles found</div>
            {rows if rows else '<div class="text-gray-400">No social profiles found</div>'}
        </div>"""

    def _render_email_intel(self, data):
        if not data:
            return ''
        email = data.get('email', 'N/A')
        accounts = data.get('social_accounts', [])
        gravatar = data.get('gravatar', {})
        accounts_html = ''
        for sa in accounts:
            accounts_html += f'<li><a href="{sa.get("url", "#")}" class="text-blue-400 hover:text-blue-300" target="_blank">{sa.get("platform")}</a> - <span class="text-gray-400">{sa.get("confidence", 0)}</span></li>'
        return f"""
        <div class="card">
            <div class="section-title"><i class="fas fa-envelope"></i> Email Intelligence</div>
            <div class="bg-gray-800 p-3 rounded-lg mb-4">
                <div class="text-xs text-gray-400">Email Address</div>
                <div class="font-medium text-blue-400">{email}</div>
            </div>
            <div class="grid grid-cols-3 gap-4 mb-4">
                <div class="bg-gray-800 p-3 rounded-lg text-center">
                    <div class="text-xs text-gray-400 mb-1">Valid</div>
                    <div class="font-medium text-green-400">{data.get('valid', 'unknown')}</div>
                </div>
                <div class="bg-gray-800 p-3 rounded-lg text-center">
                    <div class="text-xs text-gray-400 mb-1">Gravatar</div>
                    <div class="font-medium">{'<i class="fas fa-check text-green-400"></i> Yes' if gravatar.get('found') else '<i class="fas fa-times text-red-400"></i> No'}</div>
                </div>
                <div class="bg-gray-800 p-3 rounded-lg text-center">
                    <div class="text-xs text-gray-400 mb-1">Breaches</div>
                    <div class="font-medium">{'Checked' if data.get('breaches_checked') else 'Not checked'}</div>
                </div>
            </div>
            <div class="text-sm text-gray-400 mb-2"><i class="fas fa-link mr-1"></i>Linked Social Accounts:</div>
            <ul class="list-disc list-inside space-y-1">{accounts_html if accounts_html else '<li class="text-gray-500">None found</li>'}</ul>
        </div>"""

    def _render_phone_intel(self, data):
        if not data:
            return ''
        phone = data.get('phone', 'N/A')
        location = data.get('location', {})
        social_accounts = data.get('social_accounts', [])
        social_html = ''
        for sa in social_accounts:
            status_class = 'text-green-400' if sa.get('found') else 'text-red-400'
            icon = 'fa-check' if sa.get('found') else 'fa-times'
            social_html += f'<li><i class="fas {icon} {status_class} mr-1"></i>{sa.get("platform")} <span class="text-gray-400">({sa.get("confidence", 0)})</span></li>'
        return f"""
        <div class="card">
            <div class="section-title"><i class="fas fa-phone"></i> Phone Intelligence</div>
            <div class="bg-gray-800 p-3 rounded-lg mb-4">
                <div class="text-xs text-gray-400">Phone Number</div>
                <div class="font-medium text-blue-400">{phone}</div>
            </div>
            <div class="grid grid-cols-3 gap-4 mb-4">
                <div class="bg-gray-800 p-3 rounded-lg text-center">
                    <div class="text-xs text-gray-400 mb-1">Carrier</div>
                    <div class="font-medium">{data.get('carrier', 'unknown')}</div>
                </div>
                <div class="bg-gray-800 p-3 rounded-lg text-center">
                    <div class="text-xs text-gray-400 mb-1">Type</div>
                    <div class="font-medium capitalize">{data.get('line_type', 'unknown')}</div>
                </div>
                <div class="bg-gray-800 p-3 rounded-lg text-center">
                    <div class="text-xs text-gray-400 mb-1">Location</div>
                    <div class="font-medium">{location.get('city', 'unknown')}, {location.get('state', '')}</div>
                </div>
            </div>
            <div class="text-sm text-gray-400 mb-2"><i class="fas fa-comments mr-1"></i>Messaging Apps:</div>
            <ul class="list-disc list-inside space-y-1">{social_html if social_html else '<li class="text-gray-500">None detected</li>'}</ul>
        </div>"""

    def _render_username_matches(self, data):
        if not data:
            return ''
        found = {k: v for k, v in data.items() if v.get('found')}
        rows = ''
        for platform, info in list(found.items())[:20]:
            conf = info.get('confidence', 0)
            conf_class = 'badge-success' if conf >= 0.8 else ('badge-warning' if conf >= 0.6 else 'badge-info')
            rows += f"""
            <div class="profile-row">
                <div class="flex items-center gap-2">
                    <i class="fab fa-{platform.lower()} text-gray-400 icon"></i>
                    <span class="font-medium capitalize">{platform}</span>
                    <span class="badge {conf_class}">{conf}</span>
                </div>
                <a href="{info.get('url', '#')}" target="_blank" class="text-blue-400 hover:text-blue-300 text-sm">
                    {info.get('url', 'N/A')} <i class="fas fa-external-link-alt ml-1"></i>
                </a>
            </div>"""
        return f"""
        <div class="card">
            <div class="section-title"><i class="fas fa-globe"></i> Username Matches</div>
            <div class="text-sm text-gray-400 mb-4">{len(found)} platforms found</div>
            {rows if rows else '<div class="text-gray-400">No username matches found</div>'}
        </div>"""

    def _render_breaches(self, data):
        if not data:
            return ''
        rows = ''
        for key, info in data.items():
            if info.get('breaches_found', 0) > 0:
                conf = info.get('confidence', 0)
                conf_class = 'badge-danger' if conf >= 0.8 else ('badge-warning' if conf >= 0.5 else 'badge-info')
                rows += f"""
                <div class="profile-row">
                    <div>
                        <div class="font-medium capitalize">{key} Search</div>
                        <div class="text-sm text-red-400"><i class="fas fa-exclamation-triangle mr-1"></i>{info.get('breaches_found', 0)} breaches found</div>
                    </div>
                    <div class="text-right">
                        <div class="text-sm text-gray-300">{', '.join(info.get('sources', []))}</div>
                        <span class="badge {conf_class} mt-1 inline-block">confidence: {conf}</span>
                    </div>
                </div>"""
        return f"""
        <div class="card">
            <div class="section-title"><i class="fas fa-shield-alt"></i> Breach Data</div>
            {rows if rows else '<div class="text-gray-400"><i class="fas fa-check-circle text-green-400 mr-1"></i>No breach data found</div>'}
        </div>"""

    def _render_darkweb(self, data):
        if not data:
            return ''
        results = data.get('results', [])
        rows = ''
        for r in results:
            risk = r.get('risk_level', 'unknown')
            risk_class = 'badge-danger' if risk == 'high' else ('badge-warning' if risk == 'medium' else 'badge-info')
            risk_icon = 'fa-skull-crossbones' if risk == 'high' else ('fa-exclamation-triangle' if risk == 'medium' else 'fa-info-circle')
            rows += f"""
            <div class="profile-row">
                <div>
                    <div class="font-medium">{r.get('site', 'Unknown')}</div>
                    <span class="badge {risk_class}"><i class="fas {risk_icon} mr-1"></i>{risk}</span>
                </div>
                <div class="text-right text-sm text-gray-400">
                    <div>{r.get('type', 'mention')}</div>
                    <div>confidence: {r.get('confidence', 0)}</div>
                </div>
            </div>"""
        return f"""
        <div class="card">
            <div class="section-title"><i class="fas fa-user-secret"></i> Dark Web Mentions ({data.get('total_matches', 0)})</div>
            {rows if rows else '<div class="text-gray-400">No dark web mentions found</div>'}
        </div>"""

    def _render_face_matches(self, data):
        if not data:
            return ''
        results = data.get('results', {})
        count = len(results)
        rows = ''
        for platform, info in results.items():
            conf = info.get('confidence', 0)
            conf_class = 'badge-success' if conf >= 0.7 else ('badge-warning' if conf >= 0.5 else 'badge-info')
            rows += f"""
            <div class="profile-row">
                <div class="flex items-center gap-2">
                    <span class="font-medium capitalize">{platform}</span>
                    <span class="badge {conf_class}">{conf}</span>
                </div>
                <a href="{info.get('profile', '#')}" target="_blank" class="text-blue-400 text-sm">
                    View Profile <i class="fas fa-external-link-alt ml-1"></i>
                </a>
            </div>"""
        return f"""
        <div class="card">
            <div class="section-title"><i class="fas fa-face-smile"></i> Face Matches ({count} platforms)</div>
            {rows if rows else '<div class="text-gray-400">No face matches found</div>'}
        </div>"""

    def _render_reverse_image(self, data):
        if not data:
            return ''
        engines = data.get('engines', {})
        engine_rows = ''
        for engine, info in engines.items():
            status_class = 'text-green-400' if info.get('found') else 'text-red-400'
            icon = 'fa-check-circle' if info.get('found') else 'fa-times-circle'
            engine_rows += f'<li><i class="fas {icon} {status_class} mr-2"></i><span class="capitalize">{engine}</span></li>'
        return f"""
        <div class="card">
            <div class="section-title"><i class="fas fa-camera"></i> Reverse Image Search</div>
            <div class="text-sm text-gray-400 mb-4">Total web matches: <span class="text-white font-medium">{data.get('total_web_matches', 0)}</span></div>
            <div class="text-sm text-gray-400 mb-2">Search Engines:</div>
            <ul class="list-disc list-inside space-y-1">{engine_rows if engine_rows else '<li class="text-gray-500">No engines searched</li>'}</ul>
        </div>"""

    def _render_exif(self, data):
        if not data or not data.get('exif_found'):
            return ''
        camera = data.get('camera', {})
        gps = data.get('gps', {})
        dt = data.get('datetime', {})
        sw = data.get('software', {})
        return f"""
        <div class="card">
            <div class="section-title"><i class="fas fa-info-circle"></i> EXIF Data</div>
            <div class="grid grid-cols-2 gap-4">
                <div class="bg-gray-800 p-3 rounded-lg">
                    <div class="text-xs text-gray-400 mb-1">Camera</div>
                    <div class="font-medium text-sm">{camera.get('make', 'N/A')} {camera.get('model', 'N/A')}</div>
                </div>
                <div class="bg-gray-800 p-3 rounded-lg">
                    <div class="text-xs text-gray-400 mb-1">Date/Time</div>
                    <div class="font-medium text-sm">{dt.get('original', 'N/A')}</div>
                </div>
                <div class="bg-gray-800 p-3 rounded-lg">
                    <div class="text-xs text-gray-400 mb-1">Location</div>
                    <div class="font-medium text-sm">{data.get('location', 'N/A')}</div>
                </div>
                <div class="bg-gray-800 p-3 rounded-lg">
                    <div class="text-xs text-gray-400 mb-1">Coordinates</div>
                    <div class="font-medium text-sm">{gps.get('lat', 'N/A')}, {gps.get('lng', 'N/A')}</div>
                </div>
            </div>
            <div class="text-xs text-gray-400 mt-3">
                <i class="fas fa-code mr-1"></i>Software: {sw.get('name', 'N/A')} | 
                <i class="fas fa-cog mr-1"></i>ISO: {camera.get('iso', 'N/A')} | 
                <i class="fas fa-aperture mr-1"></i>Aperture: {camera.get('aperture', 'N/A')}
            </div>
        </div>"""

    def _render_graph(self, graph_data):
        if not graph_data or not graph_data.get('nodes'):
            return ''
        nodes = graph_data.get('nodes', {})
        edges = graph_data.get('edges', [])
        return f"""
        <div class="card">
            <div class="section-title"><i class="fas fa-project-diagram"></i> Relationship Graph</div>
            <div class="text-sm text-gray-400 mb-4">{len(nodes)} nodes, {len(edges)} connections</div>
            <div class="graph-container">
                <div id="graph" style="height: 500px;"></div>
                <script>
                    const graph = {json.dumps(graph_data)};
                    const width = document.getElementById('graph').clientWidth || 800;
                    const height = 500;
                    const svg = d3.select('#graph').append('svg').attr('width', width).attr('height', height);
                    const nodeData = Object.entries(graph.nodes).map(([id, n]) => ({{...n, id}}));
                    const linkData = graph.edges.map(e => ({{source: e.source, target: e.target, relationship: e.relationship}}));
                    const simulation = d3.forceSimulation(nodeData)
                        .force('link', d3.forceLink(linkData).id(d => d.id).distance(120))
                        .force('charge', d3.forceManyBody().strength(-400))
                        .force('center', d3.forceCenter(width / 2, height / 2));
                    const link = svg.append('g').selectAll('line').data(linkData).enter().append('line')
                        .attr('stroke', '#4b5563').attr('stroke-width', 2).attr('stroke-opacity', 0.6);
                    const node = svg.append('g').selectAll('g').data(nodeData).enter().append('g');
                    node.append('circle')
                        .attr('r', 10)
                        .attr('fill', d => d.type === 'person' ? '#3b82f6' : (d.type === 'account' ? '#10b981' : (d.type === 'email' ? '#f59e0b' : '#ef4444')))
                        .attr('stroke', '#1f2937').attr('stroke-width', 2);
                    node.append('text')
                        .text(d => d.label.substring(0, 15))
                        .attr('x', 12).attr('y', 4)
                        .attr('fill', '#d1d5db')
                        .attr('font-size', '10px');
                    node.append('title').text(d => d.label);
                    simulation.on('tick', () => {{
                        link.attr('x1', d => d.source.x).attr('y1', d => d.source.y).attr('x2', d => d.target.x).attr('y2', d => d.target.y);
                        node.attr('transform', d => `translate(${{d.x}},${{d.y}})`);
                    }});
                </script>
            </div>
        </div>"""
